POST http://localhost:3000/checkout HTTP/1.1
content-type: application/json
Authorization: Bearer TEST-2058488789455694-120321-a260c22a9c7416692e07f283a9289c5c-259268948

{
  "music": "https://www.youtube.com/watch?v=VnjdikpgR0E",
  "stared_at": "2024-08-27T23:41",
  "message": "Eu te amo!",
  "plan": "basic",
  "coupleName": "Eduardo e Fernanda",
  "email": "eduardo@gmail.com"
}

###

POST http://localhost:3000/create_payment HTTP/1.1
content-type: application/json
Authorization: Bearer TEST-2058488789455694-120321-a260c22a9c7416692e07f283a9289c5c-259268948

{
  "music": "https://www.youtube.com/watch?v=VnjdikpgR0E",
  "stared_at": "2024-08-27T23:41",
  "message": "Eu te amo!",
  "plan": "basic",
  "coupleName": "Eduardo e Fernanda",
  "email": "eduardo@gmail.com"
}
